### ISSUE TITLE
Project lacks license or copying file to determine license for distribution.

### ISSUE THREAD

**Issue by Justinzobel** [linuxdeepin/dde-session-shell-snipe#2]

**Comment by felixonmars** [comment]
There are https://github.com/linuxdeepin/dde-session-shell/blob/master/LICENSE and also https://github.com/linuxdeepin/dde-session-shell/blob/master/debian/copyright. What's missing here?

**Comment by Justinzobel** [comment]
Note to self, open your eyes.
