### ISSUE TITLE
锁屏界面视频播放按钮图标呈椭圆状态

### ISSUE THREAD

**Issue by asterwyx** [linuxdeepin/dde-session-shell-snipe#299]
### SUMMARY | 问题概要

当机器的分辨率处于或者低于1920x1080时，锁屏界面的音视频控制按钮呈现椭圆状态。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: deepin V23 Alpha2
Package: dde-session-shell 6.0.6

### PRE-REQUIREMENT | 预置条件

测试机器分辨率调整到1920x1080或更低

### STEPS TO REPRODUCE | 复现步骤

1. 播放一个视频/音乐
2. 使用快捷键 super+L 进入锁屏界面，观察桌面下方的视频播放按钮图标展示

### OBSERVED RESULT | 观察到的结果

1920x1080分辨率或更低下，锁屏界面视频播放按钮图标呈椭圆状态。

### EXPECTED RESULT | 期望的结果

视频播放的图标和右侧网络图标保持一致，圆形。

### ADDITIONAL INFORMATION | 额外补充

![image](https://user-images.githubusercontent.com/46272753/226275223-08ac2e63-6daa-4399-9cdc-fe43af32290d.png)

**Comment by asterwyx** [comment]
低分屏需要开启1.25倍缩放。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
