### ISSUE TITLE
登录界面无法切换回预期的锁屏界面

### ISSUE THREAD

**Issue by asterwyx** [linuxdeepin/dde-session-shell-snipe#300]
### SUMMARY | 问题概要

多用户，用户1锁屏界面切换用户，切换至用户2的登录界面后，未登录再切回用户1显示登录界面。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: deepin V23 Alpha2
Package: dde-session-shell 6.0.5.1

### PRE-REQUIREMENT | 预置条件

存在多用户，用户1为“登录”状态，用户2为“未登录”状态；登录进入用户1的桌面

### STEPS TO REPRODUCE | 复现步骤

1. super + L 进行锁屏，点击“切换用户”，选择用户2，进入用户2登录界面
2. 点击切换用户，选择用户1，观察界面显示

### OBSERVED RESULT | 观察到的结果

显示用户1的登录界面

### EXPECTED RESULT | 期望的结果

应进入用户1的锁屏界面

### ADDITIONAL INFORMATION | 额外补充

登录界面显示“->”图标，无法启用截图录屏，显示有wayland入口；锁屏界面显示图标显示为“锁”图标，可启用截图录屏，无wayland入口
![image](https://user-images.githubusercontent.com/46272753/226273306-5a6ed2bc-c87a-4d98-8146-bdc742e1d828.png)
以上为切换用户前锁屏界面
![image](https://user-images.githubusercontent.com/46272753/226274721-6a2e09a5-54fe-4ca2-b1c1-24adfc9fa542.png)

https://user-images.githubusercontent.com/46272753/226274950-d860a00b-2ee9-4b9f-9d51-c0c95bbf51bc.mp4

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
