### ISSUE TITLE
帐户密码已过期时修改密码界面显示异常

### ISSUE THREAD

**Issue by asterwyx** [linuxdeepin/dde-session-shell-snipe#302]
### SUMMARY | 问题概要

帐户密码已过期，修改密码界面显示异常。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: deepin V23 Alpha2
Package:
dde-control-center 6.0.6.1
dde-session-shell 6.0.5.1

### PRE-REQUIREMENT | 预置条件

高分屏机器，显示-屏幕缩放调整为1.75；低分屏机器，显示-屏幕缩放调整为1.25。

### STEPS TO REPRODUCE | 复现步骤

1. 控制中心-帐户-密码有效天数修改为1；
2. 电源控制按钮-注销，观察界面显示。

### OBSERVED RESULT | 观察到的结果

界面应显示为锁屏界面，中文环境下头像和用户名称重合，英文环境下“密码提示”框显示异常提示文字过小。

### EXPECTED RESULT | 期望的结果

界面应显示为登录界面，中文环境下头像和用户名称不应重合，英文环境下“密码提示”框显示正常。

### ADDITIONAL INFORMATION | 额外补充

1. 系统已安装多天，或在修改密码有效天数后修改本地时间，注销后显示修改密码界面；
2. 锁屏界面显示为“锁”图标，登录界面显示为“->”图标。
![image](https://user-images.githubusercontent.com/46272753/226277048-d761f49f-40d3-4485-9345-07d9d1a2ccde.png)
![image](https://user-images.githubusercontent.com/46272753/226277073-3aa601b0-b5dc-4e8f-b310-590077adec1e.png)
![image](https://user-images.githubusercontent.com/46272753/226277092-251d28dd-c0f8-45c9-84fe-e5621cb77547.png)

**Comment by babyfengfjx** [comment]
@SuperEffie  请在最新版本回归验证。

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
【版本信息】：dde-session-shell:6.0.8
【验证结论】：已修复，关闭此bug
【截图信息】：
![过期1](https://user-images.githubusercontent.com/58986464/233817282-1fc55206-255a-4f96-89fe-70397a3ad2ed.jpg)
![过期2](https://user-images.githubusercontent.com/58986464/233817284-82705dbd-f22e-40a8-9460-3be1bb9735a4.jpg)

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
【版本信息】：dde-session-shell:6.0.8
【验证结论】：已修复，关闭此bug
【截图信息】：
![过期1](https://user-images.githubusercontent.com/58986464/233817282-1fc55206-255a-4f96-89fe-70397a3ad2ed.jpg)
![过期2](https://user-images.githubusercontent.com/58986464/233817284-82705dbd-f22e-40a8-9460-3be1bb9735a4.jpg)
