### ISSUE TITLE
登录界面屏幕键盘无法正常输入字符

### ISSUE THREAD

**Issue by asterwyx** [linuxdeepin/dde-session-shell-snipe#306]
### SUMMARY | 问题概要

登录界面，DDE-X11模式切换到DDE-Wayland模式，屏幕键盘无法正常输入字符。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: deepin V23 Alpha2
Packages:
dde-control-center 6.0.2.1+u013
dde-daemon 6.0.2+u007
dde-session-shell 6.0.1+u011

### PRE-REQUIREMENT | 预置条件

N/A

### STEPS TO REPRODUCE | 复现步骤

1. 注销系统
2. 登录界面
3. 将DDE-X11模式切换到DDE-Wayland模式
4. 点击屏幕键盘图标
5. 查看屏幕键盘输入功能是否正常

### OBSERVED RESULT | 观察到的结果

屏幕键盘无法正常输入字符

### EXPECTED RESULT | 期望的结果

屏幕键盘可以正常输入字符

### ADDITIONAL INFORMATION | 额外补充

https://user-images.githubusercontent.com/46272753/217418489-0e6fd003-5a85-4bc4-ba1a-714bcaba44b3.mp4
[dde_log_1.tar.gz](https://github.com/linuxdeepin/developer-center/files/10681302/dde_log_1.tar.gz)
[version-20220720.log](https://github.com/linuxdeepin/developer-center/files/10681305/version-20220720.log)

**Comment by zccrs** [comment]
在Wayland模式下先禁用屏幕键盘。 @meiyixiang

**Comment by zccrs** [comment]
可以新建一个issue处理，这个issue搁置。

**Comment by asterwyx** [comment]
此问题需要测试帮忙复现一下， @babyfengfjx。

**Comment by babyfengfjx** [comment]
@SuperEffie  可以尝试在最新版本复现，如果目前设备均无法复现，可以以偶现问题跟踪。

**Comment by SuperEffie** [comment]
@asterwyx    在v23 beta2中登录界面，可以正常使用屏幕键盘输入字符。issue中录屏信息是alpha版本，wayland模式已做修改
【录屏信息】：
切换为wayland模式时，登录界面中正常使用屏幕键盘
https://github.com/linuxdeepin/dde-session-shell/assets/58986464/7066bddf-2876-4789-8f3e-91efbb60067f
切换为wayland模式后进入桌面，无法正常使用屏幕键盘，目前在Wayland模式下先禁用屏幕键盘，暂不跟踪
https://github.com/linuxdeepin/dde-session-shell/assets/58986464/726f0269-8bec-405a-b782-bfc43f95eb10

**Comment by SuperEffie** [comment]
【问题备注】：该问题先做关闭处理。alpha与beta中的wayland模式不同，v23 beta中无法复现以上问题。
