### ISSUE TITLE
dde-lock(5.4.88)：提示鉴定故障并一直在清空输入

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/dde-session-shell-snipe#40]
https://user-images.githubusercontent.com/1880237/140069845-d0e0ec0d-e085-4a74-85c1-28e306fe8e79.mp4

Uploading 2021年11月02日 屏幕视频 14时46分45秒.mp4…

**Comment by JasonYinCN** [comment]
终端验证会不会提示鉴定故障？

**Comment by hillwoodroc** [comment]
终端验证？终端怎么验证这个？

**Comment by hillwoodroc** [comment]
自己解决了，是因为用了肥猫的补丁。
